spring.application.name=GymManagementApplication

# SERVER PORT
server.port = 8080

# = DATABASE CONFIG

spring.datasource.url = jdbc:mysql://localhost:3306/gym_management_db
spring.datasource.username = root
spring.datasource.password = root
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

# = JPA / HIBERNATE CONFIG

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# = VALIDATION

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
